//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBase.Data.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatVal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatVal()
        {
            this.ArticleContents = new HashSet<ArticleContent>();
            this.Articles_KnowledgeArea = new HashSet<Article>();
            this.Articles_Theme = new HashSet<Article>();
            this.CatParents0 = new HashSet<CatVal>();
            this.CatParents1 = new HashSet<CatVal>();
            this.CatParents2 = new HashSet<CatVal>();
            this.CatParents3 = new HashSet<CatVal>();
        }
    
        public long CatValId { get; set; }
        public long CatTypeId { get; set; }
        public string Val { get; set; }
        public string Description { get; set; }
        public Nullable<long> CatParent0 { get; set; }
        public Nullable<long> CatParent1 { get; set; }
        public Nullable<long> CatParent2 { get; set; }
        public Nullable<long> CatParent3 { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleContent> ArticleContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles_KnowledgeArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles_Theme { get; set; }
        public virtual CatType CatType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatVal> CatParents0 { get; set; }
        public virtual CatVal CatVal_CatParent0 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatVal> CatParents1 { get; set; }
        public virtual CatVal CatVal_CatParent1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatVal> CatParents2 { get; set; }
        public virtual CatVal CatVal_CatParent2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatVal> CatParents3 { get; set; }
        public virtual CatVal CatVal_CatParent3 { get; set; }
    }
}
