//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBase.Data.Model2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KBaseEntitiesSC : DbContext
    {
        public KBaseEntitiesSC()
            : base("name=KBaseEntitiesSC")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticleContent> ArticleContents { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<CatType> CatTypes { get; set; }
        public virtual DbSet<CatVal> CatVals { get; set; }
    }
}
