//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBase.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleContent
    {
        public Guid ArticleContentId { get; set; }
        public Guid ArticleId { get; set; }
        public long ObjectTypeId { get; set; }
        public byte[] Object { get; set; }
        public string ObjectUrl { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<long> ObjectIndex { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual CatVal ObjectType { get; set; }
    }
}
