//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBase.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatVal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatVal()
        {
            this.CatVal1 = new HashSet<CatVal>();
            this.CatVal11 = new HashSet<CatVal>();
            this.CatVal12 = new HashSet<CatVal>();
            this.CatVal13 = new HashSet<CatVal>();
            this.Article = new HashSet<Article>();
            this.Article1 = new HashSet<Article>();
            this.ArticleContent = new HashSet<ArticleContent>();
        }
    
        public long CatValId { get; set; }
        public long CatTypeId { get; set; }
        public string Val { get; set; }
        public string Description { get; set; }
        public Nullable<long> CatParent0 { get; set; }
        public Nullable<long> CatParent1 { get; set; }
        public Nullable<long> CatParent2 { get; set; }
        public Nullable<long> CatParent3 { get; set; }
    
        public virtual CatType CatType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatVal> CatVal1 { get; set; }
        public virtual CatVal CatValCatParent3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatVal> CatVal11 { get; set; }
        public virtual CatVal CatValCatParent2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatVal> CatVal12 { get; set; }
        public virtual CatVal CatValCatParent1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatVal> CatVal13 { get; set; }
        public virtual CatVal CatValCatParent0 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Article1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleContent> ArticleContent { get; set; }
    }
}
